/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.subjects;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SubjectStandaloneSetup extends SubjectStandaloneSetupGenerated {

	public static void doSetup() {
		new SubjectStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
