/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.subjects.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import snn.apds.dsl.subjects.SubjectRuntimeModule;
import snn.apds.dsl.subjects.SubjectStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SubjectIdeSetup extends SubjectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SubjectRuntimeModule(), new SubjectIdeModule()));
	}
	
}
