/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.prototypes.ide;


/**
 * Use this class to register ide components.
 */
public class PrototypeIdeModule extends AbstractPrototypeIdeModule {
}
