/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.prototypes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PrototypeUiModule extends AbstractPrototypeUiModule {

	public PrototypeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
