/*
 * generated by Xtext 2.29.0
 */
package snn.apds.dsl.subjects.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SubjectUiModule extends AbstractSubjectUiModule {

	public SubjectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
